name: 'medical_warehouse'
version: '1.0.0'
config-version: 2

# This setting configures the profile name that dbt will look for in profiles.yml
profile: 'medical_warehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  medical_warehouse:
    # Configured materializations for specific folders
    staging:
      +materialized: view
    marts:
      +materialized: table
